services:
  db:
    image: mysql:8.4
    container_name: intranet_academica_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: intranet
      MYSQL_USER: intranet
      MYSQL_PASSWORD: intranet
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
